config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  get 'contact' => 'pages#contact'
  get 'about' => 'pages#about'
  get 'help' => 'pages#help'
  get 'signup' => 'users#new'

  root 'pages#home'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	@titre = "Accueil"
  end

  def contact
  	@titre = "Contact"
  end
  def about
  	@titre = "A Propos"
  end
  def help
  	@titre = "Aide"  	
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@titre = "Inscription"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

#retournons un titre en fonction de la situation
def titre
	base_titre= "App du Tutoriel Ruby on Rails"
	if @titre==nil
		base_titre
	else
		"#{base_titre} | #{@titre}"
	end
end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "À Propos", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
      <li><a href="http://www.railstutorial.org/">Tutoriel Rails</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <!-- <img src="../../asset/image/logo.png" alt="Logo Ruby on Rails" id="RoR"> -->
  <%= image_tag("logo.png", :alt => "Logo Ruby on Rails", :class=>"RoR") %>
  <nav class="round">
    <ul>
      <li><%= link_to "Accueil", root_path %></li>
      <li><%= link_to "Aide", help_path %></li>
      <li><%= link_to "Inscription", signup_path %></li>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
    	<title><%= titre %></title>
    	<%= csrf_meta_tag %>
    	<%= stylesheet_link_tag 'application'%>
  	</head>
  	<body>
		<div class="container">
      		<%= render 'layouts/header'%>
      		<section class="round">
        		<%= yield %>
      		</section>
    		<%= render 'layouts/footer'%>
    	</div>


  	</body>
</html>

app/views/pages/about.html.erb
<h1>About Us</h1>
<p>
  <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  est un projet de livre et de screencasts pour apprendre le développement web
  avec <a href="http://rubyonrails.org/">Ruby on Rails</a>. C'est l'Application Exemple de ce tutoriel.
</p>

app/views/pages/contact.html.erb
<h1>Contact</h1>
<p>
  Contact du Tutoriel Ruby on Rails à propos de l'Application Exemple à la
  <a href="http://railstutorial.org/feedback">page de feedback</a>.
</p>

app/views/pages/help.html.erb
<h1>Aide</h1>
<p>
  Obtenez de l'aide sur le Tutoriel Ruby on Rails sur la
  <a href="http://railstutorial.org/help">page d'aide du Tutoriel Rails</a>.
  Pour obtenir de l'aide sur cette Application Exemple, voyez le 
  <a href="http://railstutorial.org/book">livre du Tutoriel Rails</a>.
</p>

app/views/pages/home.html.erb
<h1>Sample App</h1>
<p>
  C'est la page d'accueil de l'Application Exemple du
  <a href="http://railstutorial.org/">Tutoriel Ruby on Rails</a>.
</p>
<%= link_to "S'inscrire !", signup_path, :class => "signup_button" %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>